### PR TITLE
Arbitrary range types implementation. Resolves #66

### LINKED ISSUE #66: Support for arbitrary range types
*first of all, tag this as "feature-request" "discussion" etc, for the first time I'm not coming here with a bug report :P*

I've been thinking about reflecting any kind of iterable range type. By range I mean any type where calls to std::begin() and std::end() are valid.

I see two advantages of implementing that interface:

 - **Out of the box support for any container**: As long as you're doing a foreach loop (which is the case in most of the template loops) it works. Of course we could provide a fake size() method that does std::distance(), for the uncommon case an user applies a length filter on the range.

 - **Lazy ranges**: This could be a game changer. By accepting arbitrary range types users could pass lazy ranges to the template, which means true zero-copy API binding. In my case, with @foonathan's cppast, a coroutine range implementing the AST visit comes to my mind.

### PR DESCRIPTION
**Pull request by flexferrum**

### CODE REVIEW

File: include/jinja2cpp/generic_list_iterator.h [hunk 1]
```diff
@@ -0,0 +1,41 @@
+#ifndef JINJA2_GENERIC_LIST_ITERATOR_H
+#define JINJA2_GENERIC_LIST_ITERATOR_H
+
+#include "generic_list.h"
+#include "value.h"
+
+namespace jinja2
+{
+
+class GenericListIterator
```
Comment (flexferrum) [inline include/jinja2cpp/generic_list_iterator.h]: Implement this

File: include/jinja2cpp/reflected_value.h [hunk 2]
```diff
@@ -105,47 +105,157 @@ using IsReflectedType = std::enable_if_t<TypeReflection<T>::value>;
 
 struct ContainerReflector
 {
+#if 0
```
Comment (flexferrum) [inline include/jinja2cpp/reflected_value.h]: Remove

File: include/jinja2cpp/reflected_value.h [hunk 3]
```diff
@@ -105,47 +105,157 @@ using IsReflectedType = std::enable_if_t<TypeReflection<T>::value>;
...
+        {
+            delete static_cast<Enumerator<It>*>(e);
+        }
+    };
+
+    template<typename T>
+    struct ValueItemAccessor : ListItemAccessor, IndexBasedAccessor
     {
         T m_value;
+        // Indexer<T> m_indexer;
```
Comment (flexferrum) [inline include/jinja2cpp/reflected_value.h]: Remove

File: include/jinja2cpp/reflected_value.h [hunk 4]
```diff
@@ -105,47 +105,157 @@ using IsReflectedType = std::enable_if_t<TypeReflection<T>::value>;
 
 struct ContainerReflector
```
Comment (flexferrum) [inline include/jinja2cpp/reflected_value.h]: Add reflectors for generated ranges and ranges.v3 library

File: src/expression_evaluator.cpp [hunk 5]
```diff
@@ -345,7 +345,7 @@ InternalValue CallExpression::CallGlobalRange(RenderContext& values)
             return InternalValue();
     }
 
-    class RangeGenerator : public ListAccessorImpl<RangeGenerator>
+    class RangeGenerator : public IndexedListAccessorImpl<RangeGenerator>
```
Comment (flexferrum) [inline src/expression_evaluator.cpp]: Replace with function-generated list

File: src/filters.cpp [hunk 6]
```diff
@@ -568,41 +568,76 @@ InternalValue SequenceAccessor::Filter(const InternalValue& baseVal, RenderConte
...
+
     switch (m_mode)
     {
     case FirstItemMode:
-        result = list.GetSize() == 0 ? InternalValue() : list.GetValueByIndex(0);
+        if (listSize)
+            result = list.GetValueByIndex(0);
+        else
+        {
+            auto it = list.begin();
```
Comment (flexferrum) [inline src/filters.cpp]: Think about generic conversion from generator-based list to indexed list.

File: src/filters.cpp [hunk 7]
```diff
@@ -616,11 +651,26 @@ InternalValue SequenceAccessor::Filter(const InternalValue& baseVal, RenderConte
     }
     case ReverseMode:
     {
-        InternalValueList resultList(list.GetSize());
-        for (std::size_t n = 0; n < list.GetSize(); ++ n)
-            resultList[list.GetSize() - n - 1] = list.GetValueByIndex(n);
+        if (listSize)
+        {
+            auto size = listSize.value();
```
Comment (flexferrum) [inline src/filters.cpp]: Replace with generator-based list

File: src/filters.cpp [hunk 8]
```diff
@@ -879,16 +929,16 @@ struct ValueConverterImpl : visitors::BaseVisitor<>
     }
 
     template<typename CharT>
-    struct StringAdapter : public ListAccessorImpl<StringAdapter<CharT>>
+    struct StringAdapter : public IndexedListAccessorImpl<StringAdapter<CharT>>
```
Comment (flexferrum) [inline src/filters.cpp]: Replace with generator-based list

File: src/filters.cpp [hunk 9]
```diff
@@ -898,15 +948,15 @@ struct ValueConverterImpl : visitors::BaseVisitor<>
         const string m_str;
     };
 
-    struct Map2ListAdapter : public ListAccessorImpl<Map2ListAdapter>
+    struct Map2ListAdapter : public IndexedListAccessorImpl<Map2ListAdapter>
```
Comment (flexferrum) [inline src/filters.cpp]: Replace with generator-based list

File: src/internal_value.cpp [hunk 10]
```diff
@@ -54,17 +57,32 @@ struct SubscriptionVisitor : public visitors::BaseVisitor<>
...
+
+    CallParams callParams;
+    return callable->GetExpressionCallable()(callParams, *values);
 }
 
-InternalValue Subscript(const InternalValue& val, const std::string& subscript)
+InternalValue Subscript(const InternalValue& val, const std::string& subscript, RenderContext* values)
 {
-    return Apply2<SubscriptionVisitor>(val, InternalValue(subscript));
+    return Subscript(val, InternalValue(subscript), values); // Apply2<SubscriptionVisitor>(val, InternalValue(subscript));
```
Comment (flexferrum) [inline src/internal_value.cpp]: Remove comment

File: src/internal_value.cpp [hunk 11]
```diff
@@ -270,6 +332,110 @@ ListAdapter ListAdapter::CreateAdapter(ValuesList&& values)
...
+        }
+    private:
+        size_t m_listSize;
+        GenFn m_fn;
+    };
+
+    return ListAdapter([accessor = Adapter(listSize, std::move(fn))]() {return &accessor; });
+}
+
+#if 0
```
Comment (flexferrum) [inline src/internal_value.cpp]: Remove

File: src/statements.cpp [hunk 12]
```diff
@@ -30,22 +30,22 @@ void ForStatement::RenderLoop(const InternalValue& loopVal, OutStream& os, Rende
                 bool isSucceeded = false;
```
Comment (flexferrum) [inline src/statements.cpp]: Simplify and split onto several functions.

File: test/includes_test.cpp [hunk 13]
```diff
@@ -75,8 +77,8 @@ TEST_F(IncludeTest, TestMissingIncludesError1)
     ASSERT_EQ(1ull, extraParams.size());
     auto filesList = nonstd::get_if<jinja2::GenericList>(&extraParams[0].data());
     EXPECT_NE(nullptr, filesList);
-    EXPECT_EQ(1ull, filesList->GetSize());
-    EXPECT_EQ("missing", filesList->GetValueByIndex(0).asString());
+    EXPECT_EQ(1ull, filesList->GetSize().value());
+    // EXPECT_EQ("missing", (*filesList->begin()).asString());
```
Comment (flexferrum) [inline test/includes_test.cpp]: Fix

File: test/includes_test.cpp [hunk 14]
```diff
@@ -95,9 +97,9 @@ TEST_F(IncludeTest, TestMissingIncludesError2)
     ASSERT_EQ(1ull, extraParams.size());
     auto filesList = nonstd::get_if<jinja2::GenericList>(&extraParams[0].data());
     EXPECT_NE(nullptr, filesList);
-    EXPECT_EQ(2ull, filesList->GetSize());
-    EXPECT_EQ("missing", filesList->GetValueByIndex(0).asString());
-    EXPECT_EQ("missing2", filesList->GetValueByIndex(1).asString());
+    EXPECT_EQ(2ull, filesList->GetSize().value());
+//    EXPECT_EQ("missing", filesList->GetValueByIndex(0).asString());
```
Comment (flexferrum) [inline test/includes_test.cpp]: Fix

File: src/internal_value.cpp [hunk 15]
```diff
@@ -186,16 +204,60 @@ template<template<typename> class Holder>
 class GenericListAdapter : public IListAccessor
 {
 public:
+    struct Enumerator : public IListAccessorEnumerator
+    {
+        ListEnumeratorPtr m_enum;
+
+        Enumerator(ListEnumeratorPtr e)
```
Comment (flexferrum) [inline src/internal_value.cpp]: Add `explicit`

File: src/internal_value.cpp [hunk 16]
```diff
@@ -270,6 +332,110 @@ ListAdapter ListAdapter::CreateAdapter(ValuesList&& values)
...
+{
+    using GenFn = std::function<nonstd::optional<InternalValue>()>;
+
+    class Adapter : public IListAccessor
+    {
+    public:
+        class Enumerator : public IListAccessorEnumerator
+        {
+        public:
+            Enumerator(const GenFn* fn)
```
Comment (flexferrum) [inline src/internal_value.cpp]: Add `explicit`

File: src/internal_value.cpp [hunk 17]
```diff
@@ -270,6 +332,110 @@ ListAdapter ListAdapter::CreateAdapter(ValuesList&& values)
...
+            IListAccessorEnumerator* Transfer() override
+            {
+                auto result = new Enumerator(std::move(*this));
+                return result;
+            }
+
+        protected:
+            const GenFn* m_fn;
+            InternalValue m_current;
+            bool m_isFinished;
```
Comment (flexferrum) [inline src/internal_value.cpp]: Add initializer.
